### ISSUE TITLE
Fix segfault on recording with old FFmpeg

### ISSUE THREAD

**Issue by sniper1720** [sisco311/scrcpy-snap#10]
Hi
The package has an issue while try to record, and this issue is fixed in the last 5 day, so updating the snap package will fix this issue.
https://github.com/Genymobile/scrcpy/commit/a9c8fa305d2313bed70b2d1d756083f40e065352

**Comment by sisco311** [comment]
Done:
https://github.com/sisco311/scrcpy-snap/commit/e688c4fd7457def7734b66a47c635d1aa7a5b71b
