### ISSUE TITLE
Built in scrcpy.adb does not function.

### ISSUE THREAD

**Issue by CorgJR** [sisco311/scrcpy-snap#11]
On attempt to start scrcpy.adb devices" An empty list is displayed. The adb installed in my /usr/bin works just fine. However now that my platform-tools have been updated to  v41 I can not use my own system adb as attempting to use scrcpy through snap will attempt to kill the server. 

``

> INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>
adb server version (41) doesn't match this client (39); killing...
 daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1

**Comment by sisco311** [comment]
See: issue #4
