### ISSUE TITLE
scrcpy snap not found on debian 10/buster

### ISSUE THREAD

**Issue by improvethings** [sisco311/scrcpy-snap#19]
**Environment**

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster

$ uname -srm
Linux 5.4.0-0.bpo.4-amd64 x86_64

$ snap list
Name Version Rev Tracking Publisher Notes
core 16-2.45.2 9665 latest/stable canonical✓ core
core18 20200724 1885 latest/stable canonical✓ base
scrcpy v1.15.1 238 latest/stable sisco311 -

**Describe the bug**

I installed scrcpy via snap, but it doesn't seem to be in my $PATH. I rebooted and it's still not found

$ scrcpy
bash: scrcpy: command not found
$ whereis scrcpy
scrcpy:
$ which scrcpy
$

**Comment by sisco311** [comment]
Depending on the distro you use you may have to add the PATH manually.
