### ISSUE TITLE
Provide package for arm64?

### ISSUE THREAD

**Issue by RedHatter** [sisco311/scrcpy-snap#23]
Would it be possible to provide a snap package for arm 64?

**Comment by AzureRaptor** [comment]
@sisco311  I strongly second this request.  Is it very difficult to do a build for arm64?  It would surely benefit an increasing number of machines these days.  The newer macs IIRC, the Raspberry Pi 3, and definitely the RPi4 (which I am typing this on as we speak :grin: ) all run arm64.  I was very sad when I typed:

`sudo snap install scrcpy`

and received:

`error: snap "scrcpy" is not available on stable for this architecture (arm64)
       but exists on other architectures (amd64, i386).`

Also:
Issue discussed [here](https://github.com/Genymobile/scrcpy/issues/1662) on main scrcpy repo.

**Comment by sisco311** [comment]
Done

**Comment by AzureRaptor** [comment]
> Done

@sisco311 
THANK YOU THANK YOU THANK YOU my friend!!!
This is great to have.
