### ISSUE TITLE
ERROR: Failed to enable HID over AOA, fallback to default keyboard injection method (-K/--hid-keyboard ignored)

### ISSUE THREAD

**Issue by entodoays** [sisco311/scrcpy-snap#29]
[x] I have read the FAQ.
    [x] I have searched in existing issues.

Environment

    OS: Ubuntu 21.10
    scrcpy version 1.20
    installation method: snap
    device model: Moto G4 Plus
    Android 9

Describe the bug
The title says it all. Running scrcpy with the -K option churns out this error.
```
ERROR: Failed to enable HID over AOA, fallback to default keyboard injection method (-K/--hid-keyboard ignored)
```

**Comment by sisco311** [comment]
It should work now if you connect the snap to raw-usb:
`sudo snap refresh`
`sudo snap connect scrcpy:raw-usb`

**Comment by entodoays** [comment]
I tried both the scrcpy from the stable and from the beta channel and it still didn't work.

I'm using Wayland at the moment if that has any effect.

**Comment by jaron-l** [comment]
It works on my system:
Ubuntu 20.04 using Regolith DE (i3)

**Comment by jaron-l** [comment]
@entodoays might need to try install scrcpy from source per their instructions to verify if it is a snap issue or the base package issue.

**Comment by entodoays** [comment]
I don't think I have disc space to install the dev and build requirements. In the repos there is version 1.17.

**Comment by entodoays** [comment]
Tried scrcpy on Xorg and the issue is still there. It is not related to Wayland.

**Comment by jaron-l** [comment]
Can you put the error you are receiving?

**Comment by entodoays** [comment]
> Can you put the error you are receiving?

It's in the OP.

**Comment by sisco311** [comment]
First make sure that the snap is connected to raw-usb:
`snap connections scrcpy`

Then please check your logs for [snap policy violations](https://snapcraft.io/docs/debug-snaps#heading--debugging).

If nothing rings a bell, then you can try the snap built in debug mode. You can download it from launchpad:
[amd64](https://launchpad.net/~sisco311/+snap/scrcpy-v1.20-debug/+build/1593873) [i386](https://launchpad.net/~sisco311/+snap/scrcpy-v1.20-debug/+build/1593872l)

After installing it manually you will have to re-connect it to the raw-usb plug.

Please post any warnings and/or errors.

Thanks!

**Comment by entodoays** [comment]
Discovered that the feature works when connected to usb, but not when using
tcp/ip.

**Comment by sisco311** [comment]
https://github.com/Genymobile/scrcpy#physical-keyboard-simulation-hid

HID only works if the device is connected via USB
