### ISSUE TITLE
Bundled adb error "undefined symbol: _Z13launch_serveri"

### ISSUE THREAD

**Issue by logix2** [sisco311/scrcpy-snap#5]
The scrcpy snap doesn't work for me in Ubuntu 18.10. This looks like it's due to the bundled adb that comes with the snap. When I try to run adb from ```/snap/scrcpy/25/usr/lib/android-sdk/platform-tools```, I get this error:

```
logix@logix-desktop:/snap/scrcpy/25/usr/lib/android-sdk/platform-tools$ ./adb devices
./adb: symbol lookup error: ./adb: undefined symbol: _Z13launch_serveri
```

**Comment by sisco311** [comment]
If you have to use the builtin adb tool simply run:
`scrcpy.adb`
The command is in /var/lib/snapd/snap/bin/. But your PATH should already include this directory.

**Comment by logix2** [comment]
That's what I was missing. I see now that this was added to the readme, thanks!
