### ISSUE TITLE
Cannot run on Fedora 29: "execl failed: No such file or directory"

### ISSUE THREAD

**Issue by logix2** [sisco311/scrcpy-snap#6]
I installed the scrcpy snap on Fedora 29, and when trying to run it I get this error:
```
$ scrcpy

execl failed: No such file or directory
child exited with status 1
```
The same happens when trying to run ```scrcpy.adb```.

**Comment by sisco311** [comment]
Your issue sounds similar to: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1756793
So, first try to reboot. If that doesn't solve the problem, then try to install the core package from the beta channel: `snap refresh core --beta`
If you still run in issues, please post the output of:
`snap --version`
and
`snap interfaces scrcpy`

**Comment by logix2** [comment]
I found that bug report, and already tried to reboot and to install the beta core snap with "snap refresh core --beta", but it still doesn't work.

The output of those two commands (I reverted the core snap to stable now):
```
[logix@logix22 ~]$ snap interfaces scrcpy
Slot             Plug
:adb-support     scrcpy
:desktop         scrcpy
:desktop-legacy  scrcpy
:network         scrcpy
:opengl          scrcpy
:pulseaudio      scrcpy
:unity7          scrcpy
:wayland         scrcpy
:x11             scrcpy
[logix@logix22 ~]$ snap version
snap    2.37.4-2.fc29
snapd   2.37.4-2.fc29
series  16
fedora  29
kernel  4.19.13-300.fc29.x86_64
```

Could this be related to Fedora not using apparmor? And if so maybe you're aware of some workaround.

**Comment by CandricS** [comment]
I'm having a similar issue on Solus. I get this error:

```
$ scrcpy
execv failed: No such file or directory
```

Running it directly gives:

```
/snap/scrcpy/29/usr/local/bin/scrcpy: error while loading shared libraries: libavformat.so.57: cannot open shared object file: No such file or directory
```

However, I see that that libavformat.so.57 is in /snap/scrcpy/29/usr/lib/x86_64-linux-gnu. Could it be that scrcpy is looking for it in the wrong place?

**Comment by CandricS** [comment]
This is the output I get for `snap version`:

```
$ snap version
snap    2.38
snapd   2.38
series  16
solus   4.0
kernel  4.20.16-112.current
```

And I get this for `snap interfaces scrcpy`:

```
$ snap interfaces scrcpy
Slot             Plug
:adb-support     scrcpy
:desktop         scrcpy
:desktop-legacy  scrcpy
:network         scrcpy
:opengl          scrcpy
:pulseaudio      scrcpy
:unity7          scrcpy
:wayland         scrcpy
:x11             scrcpy
```

**Comment by sisco311** [comment]
Please check out: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1808959

Did you try any other core18 based snap on your systems? Do they work?

**Comment by CandricS** [comment]
I tried chromium and I get the same error message. I reported it on the forums so hopefully it gets fixed soon.
