### ISSUE TITLE
Scrcpy Not Launching

### ISSUE THREAD

**Issue by 2635599** [sisco311/scrcpy-snap#7]
the day before yesterday i installed scrcpy and ran it without issue like i have on my previous install of linux. today i went to launch it and it would not run no matter where i tried to launch it from, so i opened konsol and uninstalled and reinstalled. now i get the following. i'm at a lost at what to do to fix this. any ideas or suggestions would be greatly appreciated. thanks

`mg2635599@2635599s-Kubuntu:~$ sudo snap install scrcpy
scrcpy v1.9 from sisco311 installed
mg2635599@2635599s-Kubuntu:~$ scrcpy
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 1.0 MB/s (22470 bytes in 0.021s)
bind: Address already in use
ERROR: Could not listen on port 27183
mg2635599@2635599s-Kubuntu:~$ scrcpy
/usr/local/share/scrcpy/scrcpy-server.jar: 1 file pushed. 3.8 MB/s (22470 bytes in 0.006s)
bind: Address already in use
ERROR: Could not listen on port 27183
mg2635599@2635599s-Kubuntu:~$ szudo su

Command 'szudo' not found, did you mean:

  command 'sudo' from deb sudo (1.8.27-1ubuntu1)
  command 'sudo' from deb sudo-ldap (1.8.27-1ubuntu1)

Try: sudo apt install <deb name>

mg2635599@2635599s-Kubuntu:~$ sudo su
root@2635599s-Kubuntu:/home/mg2635599# scrcpy
Command 'scrcpy' is available in '/snap/bin/scrcpy'
The command could not be located because '/snap/bin' is not included in the PATH environment variable.
scrcpy: command not found
root@2635599s-Kubuntu:/home/mg2635599# 
`

kubuntu 19.04 64 bit kernel 5.1.7

**Comment by sisco311** [comment]
Don't run the snap as root (with sudo).

Try to kill the adb server before you start scrcpy:
`scrcpy.adb kill-server`
`scrcpy`

**Comment by 2635599** [comment]
i tried that and got the following.

mg2635599@2635599s-Kubuntu:~$ scrcpy.adb kill-server
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
cannot connect to daemon at tcp:5037: Connection refused
mg2635599@2635599s-Kubuntu:~$ scrcpy
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb: error: failed to get feature set: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
ERROR: "adb push" returned with value 1
mg2635599@2635599s-Kubuntu:~$

**Comment by 2635599** [comment]
hey thanks for attempting to help resolve my issue, it's much appreciated. that said i found this and have scrcpy up and running again. thanks again.

https://www.linuxuprising.com/2019/03/control-android-devices-from-your.html

https://i.imgur.com/w1xvQBU.png
