### ISSUE TITLE
How can I install different version of scrcpy with snap?

### ISSUE THREAD

**Issue by GBwuka** [sisco311/scrcpy-snap#8]
there is an Segmentation Fault bug in v1.10 in scrcpy, if I want to install v1.9 version of scrcpy using snap, how can I do?
Thank you!

**Comment by GBwuka** [comment]
can release v1.9 verison of scrcpy on snap? I need scrcpy rencently, thank you very much !
![image](https://user-images.githubusercontent.com/1592742/62925977-0f664880-bde6-11e9-83d0-314610a7d857.png)

**Comment by sisco311** [comment]
Hi,

If an older revision of the snap is still installed on your system you  can revert to it:
`snap revert scrcpy`

If not, you can download the snap package from https://github.com/sisco311/scrcpy-snap/releases and install it manually:
`snap install --dangerous ./scrcpy_v1.9_amd64.snap`

**Comment by CorgJR** [comment]
I installed fresh and can not revert, also having the same error.

**Comment by sisco311** [comment]
It would be helpful if you could share more details. Please post the error message, the OS/version you are using.
